name: Pantheon
version: '1.0.0'
main: dev.goodrich.pantheon.Pantheon
api-version: '1.21'
author: 0xBit
folia-supported: true
description: "Pantheon integrates religion data into Towny's info screens, allowing residents to set their religion and displaying breakdowns in towns and nations."
commands:
  pantheon:
    description: "Pantheon admin command (e.g. /pantheon reload religions)"
    usage: "/pantheon reload religions"
    permission: pantheon.reload
    permission-message: "You don’t have permission to view religions."
  religions:
    description: "Show server-wide religion breakdown (e.g. /religions)"
    usage: "/religions"
    permission: pantheon.view
    permission-message: "You don’t have permission to view religions."
permissions:
  pantheon.reload:
    description: "Allows reloading of religion configuration."
    default: op
  pantheon.view:
    description: "Allows viewing of total religion count on the server."
    default: true
softdepend:
  - Towny